::ampy put boot.py
ampy put .\main.py
ampy put .\htmlbase.html
::ampy put .\motorcontrol.py
::ampy put .\servocontrol.py
::ampy put .\settings.json
::ampy put .\urlparse.py
ampy put .\webserver_microdot.py
::ampy put .\wlansettings.py 